export const TransactionEnum = Object.freeze({
    CHECKED_OUT_BY_ANOTHER: "CHECKED_OUT_BY_ANOTHER",
    ON_HOLD_BY_ANOTHER: "ON_HOLD_BY_ANOTHER",
    CHECKED_OUT_BY_USER: "CHECKED_OUT_BY_USER",
    ON_HOLD_BY_USER: "ON_HOLD_BY_USER",
    AT_BORROWING_LIMIT: "AT_BORROWING_LIMIT",
    AT_HOLD_LIMIT: "AT_HOLD_LIMIT",
    BOOK_IS_AVAILABLE: "BOOK_IS_AVAILABLE",
    CAN_BORROW: "CAN_BORROW",
    CAN_HOLD: "CAN_HOLD"
});